language: python

env:
  - TOXENV=flake8
  - TOXENV=py27-Django-1.7.x
  - TOXENV=py27-Django-1.8.x
  - TOXENV=py27-Django-master
  - TOXENV=py32-Django-1.7.x
  - TOXENV=py32-Django-1.8.x
  - TOXENV=py32-Django-master
  - TOXENV=py33-Django-1.7.x
  - TOXENV=py33-Django-1.8.x
  - TOXENV=py33-Django-master
  - TOXENV=py34-Django-1.7.x
  - TOXENV=py34-Django-1.8.x
  - TOXENV=py34-Django-master

matrix:
  allow_failures:
    - env: TOXENV=py27-Django-master
    - env: TOXENV=py32-Django-master
    - env: TOXENV=py33-Django-master
    - env: TOXENV=py34-Django-master

install:
  - pip install coveralls
  - pip install tox

script:
  - tox

after_success:
  - coverage combine
  - coveralls
